/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.FornecedoresDAO;
import DAO.ProdutosDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedores;
import model.Produtos;
import model.Utilitarios;

/**
 *
 * @author Erivelton
 */
public class FormularioProdutos extends javax.swing.JFrame {

    public void listar() {
        // Cria uma instância do DAO para acessar os dados dos produtos
        ProdutosDAO dao = new ProdutosDAO();

        // Obtém a lista de produtos usando o DAO
        List<Produtos> lista = dao.listarProdutos();

        // Obtém o modelo da tabela e limpa as linhas existentes
        DefaultTableModel dados = (DefaultTableModel) tabelaprodutos.getModel();
        dados.setNumRows(0);

        // Itera sobre a lista de produtos e adiciona cada produto à tabela
        for (Produtos p : lista) {
            dados.addRow(new Object[]{
                p.getId(), // ID do produto
                p.getDescricao(), // Descrição do produto
                p.getPreco(), // Preço do produto
                p.getQtdEstoque(), // Quantidade em estoque
                p.getFornecedor().getNome()
            });
        }
    }

    /**
     * Creates new form FormularioProdutos
     */
    public FormularioProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paineldadospessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtqtdestoque = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbfornecedores = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        btnpesquisarfornecedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();
        btnnovo2 = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Descrição:");

        txtdescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescricaoActionPerformed(evt);
            }
        });
        txtdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescricaoKeyPressed(evt);
            }
        });

        btnpesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });
        btnpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnpesquisarKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Preco:");

        txtpreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });
        txtpreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprecoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Qtd Estoque:");

        txtqtdestoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtqtdestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdestoqueActionPerformed(evt);
            }
        });
        txtqtdestoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqtdestoqueKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Fornecedores:");

        cbfornecedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbfornecedores.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbfornecedoresAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbfornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbfornecedoresMouseClicked(evt);
            }
        });
        cbfornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paineldadospessoaisLayout = new javax.swing.GroupLayout(paineldadospessoais);
        paineldadospessoais.setLayout(paineldadospessoaisLayout);
        paineldadospessoaisLayout.setHorizontalGroup(
            paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                        .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnpesquisar))
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbfornecedores, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtqtdestoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        paineldadospessoaisLayout.setVerticalGroup(
            paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqtdestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbfornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Do Produto", paineldadospessoais);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Nome:");

        txtpesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        btnpesquisarfornecedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnpesquisarfornecedores.setText("Pesquisar");
        btnpesquisarfornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarfornecedoresActionPerformed(evt);
            }
        });

        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Qtd Estoque", "Fornecedor"
            }
        ));
        tabelaprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaprodutos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnpesquisarfornecedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisarfornecedores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Produtos", jPanel3);

        btnnovo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnnovo2.setText("+NOVO");
        btnnovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo2ActionPerformed(evt);
            }
        });

        btnsalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnexcluir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnexcluir.setText("EXCLUIR");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnnovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(btnnovo2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescricaoActionPerformed

    private void txtdescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescricaoKeyPressed
        // ao clicar no enter encontra usuario tbm

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String descricao = txtdescricao.getText();

            ProdutosDAO dao = new ProdutosDAO(); // Passa a conexão para o DAO
            Produtos obj = dao.buscaProdutoPorDescricao(descricao); // Busca o produto pela descrição

            obj = dao.consultaPorNome(descricao);
            cbfornecedores.removeAll();

            if (obj.getDescricao() != null) {

                txtcodigo.setText(String.valueOf(obj.getId()));
                txtdescricao.setText(obj.getDescricao());
                txtpreco.setText(String.valueOf(obj.getPreco()));
                txtqtdestoque.setText(String.valueOf(obj.getQtdEstoque()));

                Fornecedores f = new Fornecedores();
                FornecedoresDAO fdao = new FornecedoresDAO();

                cbfornecedores.getModel().setSelectedItem(f);

            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }

        }


    }//GEN-LAST:event_txtdescricaoKeyPressed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        // Botão busca produtos por descrição
        String descricao = txtdescricao.getText();

        ProdutosDAO dao = new ProdutosDAO(); // Passa a conexão para o DAO
        Produtos obj = dao.buscaProdutoPorDescricao(descricao); // Busca o produto pela descrição

        obj = dao.consultaPorNome(descricao);
        cbfornecedores.removeAll();

        if (obj.getDescricao() != null) {

            txtcodigo.setText(String.valueOf(obj.getId()));
            txtdescricao.setText(obj.getDescricao());
            txtpreco.setText(String.valueOf(obj.getPreco()));
            txtqtdestoque.setText(String.valueOf(obj.getQtdEstoque()));

            Fornecedores f = new Fornecedores();
            FornecedoresDAO fdao = new FornecedoresDAO();

            cbfornecedores.getModel().setSelectedItem(f);

        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
        }

    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtprecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Simula o clique no botão
            btnpesquisar.doClick();
        }
    }//GEN-LAST:event_txtprecoKeyPressed

    private void txtqtdestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdestoqueActionPerformed

    private void txtqtdestoqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdestoqueKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdestoqueKeyPressed

    private void cbfornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfornecedoresActionPerformed

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed

        // Obtém o texto de pesquisa e prepara a string com os curingas
        String descricao = "%" + txtpesquisa.getText() + "%";

        try {
            // Cria uma instância do ProdutosDAO
            ProdutosDAO dao = new ProdutosDAO();

            // Busca produtos por descrição
            List<Produtos> lista = dao.listarProdutosPesquisa(descricao);

            // Obtém o modelo da tabela e limpa as linhas existentes
            DefaultTableModel dados = (DefaultTableModel) tabelaprodutos.getModel();
            dados.setNumRows(0);

            // Preenche a tabela com os dados dos produtos
            for (Produtos p : lista) {
                dados.addRow(new Object[]{
                    p.getId(), // ID do produto
                    p.getDescricao(), // Descrição do produto
                    p.getPreco(), // Preço do produto
                    p.getQtdEstoque(), // Quantidade em estoque
                    p.getFornecedor() != null ? p.getFornecedor().getNome() : "Fornecedor não disponível" // Nome do fornecedor
                });
            }
        } catch (Exception e) {
            e.printStackTrace(); // Ou exiba uma mensagem de erro apropriada
        }


    }//GEN-LAST:event_txtpesquisaActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        // consulta cliente ao ser clicado

        String nome = "%" + txtpesquisa.getText() + "%";

        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> lista = dao.buscaFornecedorPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaprodutos.getModel();
        dados.setNumRows(0);

        for (Fornecedores f : lista) {
            dados.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCnpj(),
                f.getEmail(),
                f.getTelefone(),
                f.getCelular(),
                f.getCep(),
                f.getNumero(),
                f.getComplemento(),
                f.getBairro(),
                f.getCidade(),
                f.getEstado()
            });
        }
    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void btnpesquisarfornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarfornecedoresActionPerformed
        // botao pesquisar clientes

        String nome = "%" + txtpesquisa.getText() + "%";

        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarProdutos();

        DefaultTableModel dados = (DefaultTableModel) tabelaprodutos.getModel();
        dados.setNumRows(0);

        for (Produtos p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtdEstoque(),
                p.getFornecedor().getNome() // ou qualquer outro atributo relevante
            });
        }

    }//GEN-LAST:event_btnpesquisarfornecedoresActionPerformed

    private void tabelaprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutosMouseClicked
        // Pega dados da tabela produtos

// Define o painel a ser exibido (tab de produtos)
        jTabbedPane1.setSelectedIndex(0);

// Atualiza os campos com os valores selecionados na tabela de produtos
        txtcodigo.setText(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(), 0).toString());
        txtdescricao.setText(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(), 1).toString()); // Atualizado para Descrição
        txtpreco.setText(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(), 2).toString()); // Atualizado para Preço
        txtqtdestoque.setText(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(), 3).toString()); // Atualizado para Quantidade em Estoque

        Fornecedores f = new Fornecedores();
        FornecedoresDAO dao = new FornecedoresDAO();
        f = dao.consultaPorNome(tabelaprodutos.getValueAt(tabelaprodutos.getSelectedRow(), 4).toString());

        cbfornecedores.removeAllItems();
        cbfornecedores.setSelectedItem(f);

    }//GEN-LAST:event_tabelaprodutosMouseClicked

    private void cbfornecedoresAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbfornecedoresAncestorAdded
        // adicionar fornecedores
        //carregando combox

        FornecedoresDAO daof = new FornecedoresDAO();
        List<Fornecedores> listaFornecedores = daof.listarFornecedores();

        cbfornecedores.removeAllItems(); // Corrigido para removeAllItems()
        if (listaFornecedores != null) {
            for (Fornecedores f : listaFornecedores) {
                cbfornecedores.addItem(f);
            }
        }


    }//GEN-LAST:event_cbfornecedoresAncestorAdded

    private void btnnovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo2ActionPerformed
        // Botão editar produtos
        Produtos obj = new Produtos();

// Configura os dados do produto a ser editado
        obj.setDescricao(txtdescricao.getText()); // Altere para Descrição
        obj.setPreco(Double.parseDouble(txtpreco.getText())); // Altere para Preço
        obj.setQtdEstoque(Integer.parseInt(txtqtdestoque.getText())); // Altere para Quantidade em Estoque

// Configura o fornecedor associado ao produto
        Fornecedores fornecedor = (Fornecedores) cbfornecedores.getSelectedItem();
        obj.setFornecedor(fornecedor);

// Atualiza o ID do produto para garantir que o produto correto seja editado
        obj.setId(Integer.parseInt(txtcodigo.getText())); // Atualize o ID

// Instancia o DAO e chama o método para atualizar o produto
        ProdutosDAO dao = new ProdutosDAO();
        dao.alterarProduto(obj); // Altere para o método de atualização de produto

// Limpa a tela após a operação (se necessário)
        new Utilitarios().limpaTela(paineldadospessoais);

    }//GEN-LAST:event_btnnovo2ActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed

        // Botão salvar produtos
        Produtos obj = new Produtos();

        obj.setDescricao(txtdescricao.getText()); // Atualizado para Descrição
        obj.setPreco(Double.parseDouble(txtpreco.getText())); // Atualizado para Preço
        obj.setQtdEstoque(Integer.parseInt(txtqtdestoque.getText())); // Atualizado para Quantidade em Estoque

        Fornecedores f = new Fornecedores();
        f = (Fornecedores) cbfornecedores.getSelectedItem();

        obj.setFornecedor(f);

        ProdutosDAO dao = new ProdutosDAO();
        dao.cadastrarProduto(obj); // Atualizado para o método de cadastro de produto

        new Utilitarios().limpaTela(paineldadospessoais);
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed

        // Botão editar produtos
        Produtos obj = new Produtos();

// Configura os dados do produto a partir dos campos do formulário
        obj.setDescricao(txtdescricao.getText()); // Descrição do produto
        obj.setPreco(Double.parseDouble(txtpreco.getText())); // Preço do produto
        obj.setQtdEstoque(Integer.parseInt(txtqtdestoque.getText())); // Quantidade em estoque

// Define o fornecedor associado ao produto
        Fornecedores f = (Fornecedores) cbfornecedores.getSelectedItem();
        obj.setFornecedor(f);

// Atualiza o ID do produto
        obj.setId(Integer.parseInt(txtcodigo.getText()));

// Instancia o DAO e chama o método para alterar o produto
        ProdutosDAO dao = new ProdutosDAO();
        dao.alterarProduto(obj); // Método para alteração de produto

// Opcional: Limpar o formulário após a atualização (se necessário)
        new Utilitarios().limpaTela(paineldadospessoais);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // Botão excluir produtos
        Produtos obj = new Produtos();

// Configura o ID do produto a ser excluído
        obj.setId(Integer.parseInt(txtcodigo.getText()));

// Instancia o DAO e chama o método para excluir o produto
        ProdutosDAO dao = new ProdutosDAO();
        dao.excluirProduto(obj);

// Opcional: Limpar o formulário após a exclusão (se necessário)
        new Utilitarios().limpaTela(paineldadospessoais);

    }//GEN-LAST:event_btnexcluirActionPerformed

    private void cbfornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbfornecedoresMouseClicked
        // TODO add your handling code here:
        FornecedoresDAO dao = new FornecedoresDAO();
        List<Fornecedores> listaDeFornecedores = dao.listarFornecedores();
        cbfornecedores.removeAllItems();

        for (Fornecedores f : listaDeFornecedores) {
            cbfornecedores.addItem(f);
        }
    }//GEN-LAST:event_cbfornecedoresMouseClicked

    private void btnpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnpesquisarKeyPressed

    }//GEN-LAST:event_btnpesquisarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo2;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton btnpesquisarfornecedores;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox cbfornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel paineldadospessoais;
    public javax.swing.JTable tabelaprodutos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtqtdestoque;
    // End of variables declaration//GEN-END:variables
}
